// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvxErEHK9MCuTCRX9tx0o23E2ob2_CgxM',
    appId: '1:1069971628830:web:93d60a29fc842d699b5f0f',
    messagingSenderId: '1069971628830',
    projectId: 'warm-app-26064',
    authDomain: 'warm-app-26064.firebaseapp.com',
    storageBucket: 'warm-app-26064.firebasestorage.app',
    measurementId: 'G-9B9CE7XFES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF8w-e_UvANshxK3TGd1VP4SV4bXF1BUo',
    appId: '1:1069971628830:android:daa9ce39428d7e4f9b5f0f',
    messagingSenderId: '1069971628830',
    projectId: 'warm-app-26064',
    storageBucket: 'warm-app-26064.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRtjNIbMQFuTnuGXOB1jA-fzfJ6-Jt9vA',
    appId: '1:1069971628830:ios:310b9bdbb1484f149b5f0f',
    messagingSenderId: '1069971628830',
    projectId: 'warm-app-26064',
    storageBucket: 'warm-app-26064.firebasestorage.app',
    iosBundleId: 'com.example.warmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRtjNIbMQFuTnuGXOB1jA-fzfJ6-Jt9vA',
    appId: '1:1069971628830:ios:310b9bdbb1484f149b5f0f',
    messagingSenderId: '1069971628830',
    projectId: 'warm-app-26064',
    storageBucket: 'warm-app-26064.firebasestorage.app',
    iosBundleId: 'com.example.warmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvxErEHK9MCuTCRX9tx0o23E2ob2_CgxM',
    appId: '1:1069971628830:web:3da2d4dcebc76f109b5f0f',
    messagingSenderId: '1069971628830',
    projectId: 'warm-app-26064',
    authDomain: 'warm-app-26064.firebaseapp.com',
    storageBucket: 'warm-app-26064.firebasestorage.app',
    measurementId: 'G-VTDLDRC165',
  );
}
